dist: bionic
jobs:
  include:
    - stage: "Dashboard Unit Tests"
      name: "dashboard-unit-tests"
      language: node_js
      node_js:
        - "13"
      sudo: required
      before_install:
        # Remove /usr/local/bin/yarn to avoid conflicts with installed version
        - "sudo rm /usr/local/bin/yarn"
      install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - sudo echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -y -qq
        - sudo apt-get install -y -qq yarn
      script: ./unittests

    - stage: "Dashboard E2E Tests"
      name: "dashboard-e2e-tests"
      language: node_js
      node_js:
        - "13"
      sudo: required
      services:
        # allow headless browser tests
        - xvfb
      addons:
        chrome: stable
        hostname: localhost
      before_install:
        # Enable user namespace cloning
        - "sysctl kernel.unprivileged_userns_clone=1"
        # Remove /usr/local/bin/yarn to avoid conflicts with the "old" version
        # provided by the TravisCI language "node_js".
        - "sudo rm /usr/local/bin/yarn"
      install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - sudo echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -y -qq
        - sudo apt-get install -y -qq yarn
      script: ./e2etests
