#!/bin/bash

cd $(dirname ${0})

# Setup the mock'd data store configuration.
cat > mock/datastoreConfig.js <<EOF
export default {
  '/dev/datastoreConfig': {
    elasticsearch: 'http://test_domain.com',
    results: 'http://test_domain.com',
    graphql: 'http://test_domain.com',
    prefix: 'test_prefix.',
    run_index: 'test_index.',
  },
};
EOF
yarn install --network-timeout 1000000
if [[ ${?} -ne 0 ]]; then
  echo "yarn install failed!" >&2
  exit 1
fi
yarn lint
if [[ ${?} -ne 0 ]]; then
  echo "yarn lint failed!" >&2
  exit 1
fi
yarn test
if [[ ${?} -ne 0 ]]; then
  echo "yarn unit tests failed!" >&2
  exit 1
fi
exit 0
